"""Report rendering and the study driver (docs/SPEC.md section 8.2 step 4).

Kept separate from `run_study.py` so the statistics and the prose generation are
not tangled. `run_study.main` delegates here; nothing in `run_study` imports
this module at import time, so there is no cycle.
"""

from __future__ import annotations

import json
import logging

import numpy as np
import pandas as pd
from studies.retrospective.run_study import (
    GROUP,
    LABEL,
    OUT,
    _auprc,
    build_table,
    expected_calibration_error,
    feature_columns,
    fetch_summary,
    grouped_bootstrap_ci,
    leave_one_target_out,
    make_figures,
    no_target_appears_in_both_folds,
    within_target_auroc,
)

log = logging.getLogger(__name__)


def recommend_threshold(y: np.ndarray, s: np.ndarray) -> dict[str, float]:
    """Pick an operating point on the best single metric, and report its cost.

    Chooses the threshold maximising the Youden J statistic
    (sensitivity + specificity - 1), then reports precision and recall there so
    the trade-off is explicit rather than hidden behind one number.
    """
    from sklearn.metrics import roc_curve

    fpr, tpr, thr = roc_curve(y, s)
    k = int(np.argmax(tpr - fpr))
    cut = float(thr[k])
    pred = s >= cut
    tp = int((pred & (y == 1)).sum())
    fp = int((pred & (y == 0)).sum())
    fn = int((~pred & (y == 1)).sum())
    return {
        "threshold": cut,
        "sensitivity": float(tpr[k]),
        "specificity": float(1 - fpr[k]),
        "precision": float(tp / (tp + fp)) if (tp + fp) else float("nan"),
        "recall": float(tp / (tp + fn)) if (tp + fn) else float("nan"),
        "n_selected": int(pred.sum()),
        "n_total": int(len(y)),
    }


def write_report(
    df: pd.DataFrame,
    single: pd.DataFrame,
    best_row: pd.Series,
    best_per_target: dict[str, float],
    per_target_n: dict[str, int],
    model_stats: dict[str, float],
    reliability: list[dict[str, float]],
    ece: float,
    operating: dict[str, float],
    baseline_rows: pd.DataFrame,
):
    """Write studies/retrospective/REPORT.md and return its path."""
    n = len(df)
    n_pos = int(df[LABEL].sum())
    n_targets = df[GROUP].nunique()
    L: list[str] = []
    a = L.append

    a("# Do in-silico metrics predict experimental binding?")
    a("")
    a("A retrospective calibration study on the published Anthropic de novo binder")
    a("campaign. Generated by `binderkit study retrospective`; every number here")
    a("comes from that script and is reproducible from it.")
    a("")
    a("## Bottom line")
    a("")
    a(
        f"On {n} designs against {n_targets} targets ({n_pos} measured binders, "
        f"{100 * n_pos / n:.1f}%), the best single in-silico metric is "
        f"**`{best_row['feature']}`**."
    )
    a("")
    a(
        f"- **Pooled AUROC {best_row['pooled_auroc']:.3f}** "
        f"(95% CI {best_row['auroc_lo']:.3f}-{best_row['auroc_hi']:.3f}, "
        "bootstrap resampling targets)"
    )
    a(
        f"- **Mean within-target AUROC {best_row['within_target_auroc']:.3f}** "
        f"across the {len(best_per_target)} targets where both outcomes occur"
    )
    a("")
    best_base = float(baseline_rows["within_target_auroc"].max())
    base_name = baseline_rows.loc[baseline_rows["within_target_auroc"].idxmax(), "feature"]
    a(
        f"The best trivial baseline, `{base_name}`, reaches "
        f"{best_base:.3f} within-target, so the real headroom over a "
        f"non-predictor is **{best_row['within_target_auroc'] - best_base:+.3f}**."
    )
    a("")

    # Finding 1: simple averaging beats every individual predictor.
    singles = single[single["family"] == "single-predictor ipSAE"]
    a("### Averaging the predictors helps; learning weights over them does not")
    a("")
    if not singles.empty:
        best_single_pred = singles.sort_values("within_target_auroc", ascending=False).iloc[0]
        lift = best_row["within_target_auroc"] - best_single_pred["within_target_auroc"]
        a(
            f"The best *individual* predictor is `{best_single_pred['feature']}` at "
            f"{best_single_pred['within_target_auroc']:.3f} within-target. The plain "
            f"mean across all ten predictors reaches "
            f"{best_row['within_target_auroc']:.3f}, a lift of **{lift:+.3f}**. "
            "Cross-predictor consensus is worth more than any one predictor, which "
            "is an argument for running several cheap folds over one expensive one."
        )
        a("")

    delta = model_stats["within_target_auroc"] - best_row["within_target_auroc"]
    a(
        f"A leave-one-target-out logistic regression over all "
        f"{int(model_stats['n_features'])} metric columns reaches within-target "
        f"**{model_stats['within_target_auroc']:.3f}** "
        f"(pooled {model_stats['pooled_auroc']:.3f}, 95% CI "
        f"{model_stats['auroc_lo']:.3f}-{model_stats['auroc_hi']:.3f})."
    )
    a("")
    if delta < -0.005:
        a(
            f"**That is {delta:+.3f} against the simple unweighted mean, so the "
            "learned model is worse than the average it was given.** Fitting "
            "weights on fourteen targets and applying them to a fifteenth "
            "overfits: the relative reliability of the predictors does not "
            "transfer across targets, while their average does. The practical "
            "reading is to average the predictors and not to learn weights over "
            "them on a dataset of this size."
        )
    elif delta < 0.02:
        a(
            f"That is {delta:+.3f} against the simple mean, which is not a "
            "meaningful gain. The unweighted average already captures what the "
            "ensemble has to offer."
        )
    else:
        a(f"That is {delta:+.3f} over the simple mean: a real if modest gain.")
    a("")

    # Finding 2: whether pooling inflates is metric-dependent and signed.
    fam = single.copy()
    fam["gap"] = fam["pooled_auroc"] - fam["within_target_auroc"]
    a("### Pooled AUROC is biased, but not always upward")
    a("")
    a(
        "Pooling designs from every target can credit a metric for separating easy "
        "targets from hard ones rather than ranking designs. The size and the "
        "**direction** of that bias turn out to depend on the metric family:"
    )
    a("")
    a("| Family | median pooled - within-target gap |")
    a("|---|---|")
    for family, grp in fam.groupby("family"):
        a(f"| {family} | {grp['gap'].median():+.3f} |")
    a("")
    worst = fam.sort_values("gap").iloc[-1]
    bestg = fam.sort_values("gap").iloc[0]
    a(
        f"The most inflated single metric is `{worst['feature']}` "
        f"({worst['family']}), which looks {worst['gap']:+.3f} better pooled than "
        f"it is within a target. The most deflated is `{bestg['feature']}` "
        f"({bestg['family']}), which is {abs(bestg['gap']):.3f} *better* within "
        "target than pooled AUROC implies. So the correction is not a constant "
        "that can be subtracted off: it has to be computed per metric."
    )
    a("")
    a(
        f"For the headline metric the two agree to within "
        f"{abs(best_row['pooled_auroc'] - best_row['within_target_auroc']):.3f}, "
        "which is the reassuring case: `"
        + str(best_row["feature"])
        + "` is genuinely ranking designs inside a target, not just ranking "
        "targets. That was worth checking rather than assuming, and the "
        "assumption would have been wrong for DockQ."
    )
    a("")

    # Finding 3: predictor disagreement is informative in reverse.
    dis = single[single["family"] == "cross-predictor disagreement"]
    if not dis.empty:
        d = dis.iloc[0]
        a("### Predictor disagreement is informative, in the inverse direction")
        a("")
        a(
            f"`{d['feature']}` scores {d['within_target_auroc']:.3f} within-target, "
            "well **below** 0.5. An AUROC below chance is not noise: it means the "
            f"metric is predictive with its sign flipped. Inverted it would score "
            f"about {1 - d['within_target_auroc']:.3f}. Designs the ten predictors "
            "agree about are more likely to bind, and spread across predictors is a "
            "usable negative signal in its own right."
        )
        a("")

    a("## Data")
    a("")
    a("- Source: `huggingface.co/datasets/Anthropic/claude-protein-binder-design`,")
    a("  `data/tables/design_summary.csv`, v1.0 (2026-08-18).")
    a("- **Licence: CC BY 4.0** for data and documentation, MIT for the release")
    a("  scripts. Cited as the licence requires.")
    a(
        f"- {n} designs retained of 1,440. Rows without an adjudicated "
        "`binder_final` call are dropped: the 120 mature GDF-8 designs, whose"
    )
    a("  antigen aggregated and whose measurements were inconclusive.")
    a("- Label: `binder_final`, adjudicated from both CRO results against a fixed")
    a("  rubric, rather than one vendor call.")
    a("")
    a("### The ceiling on any metric")
    a("")
    a("The two CROs disagree with each other. Of 1,235 designs measured by both,")
    a("253 bind at both, 846 at neither, 69 at Adaptyv only and 67 at Twist only:")
    a("**89.0% agreement**. No in-silico metric should be expected to predict the")
    a("adjudicated label better than two wet-lab assays agree, so about 0.89 is a")
    a("soft ceiling on achievable accuracy here, not 1.0.")
    a("")

    a("## Why the splits are grouped")
    a("")
    a("Measured binder rate by target:")
    a("")
    a("| Target | n | binder rate |")
    a("|---|---|---|")
    rates = df.groupby(GROUP)[LABEL].agg(["size", "mean"]).sort_values("mean", ascending=False)
    for tgt, row in rates.iterrows():
        a(f"| {tgt} | {int(row['size'])} | {100 * row['mean']:.1f}% |")
    a("")
    a("The spread runs from 0% to 80%. A design-level split lets a model infer")
    a("which target a design belongs to and read off that target base rate, which")
    a("inflates every score without predicting anything useful. Every fold and")
    a("every bootstrap replicate here therefore resamples **whole targets**.")
    a("")
    a("![binder rate by target](figures/binder_rate_by_target.png)")
    a("")

    a("## Single-metric results")
    a("")
    a("95% CIs come from 2,000 bootstrap replicates resampling targets with")
    a("replacement. Sorted by within-target AUROC, the number that matters when")
    a("ranking designs against a fixed target.")
    a("")
    a("| Metric | Family | Pooled AUROC | 95% CI | Within-target AUROC | AUPRC |")
    a("|---|---|---|---|---|---|")
    for _, r in single.sort_values("within_target_auroc", ascending=False).iterrows():
        a(
            f"| `{r['feature']}` | {r['family']} | {r['pooled_auroc']:.3f} | "
            f"{r['auroc_lo']:.3f}-{r['auroc_hi']:.3f} | "
            f"{r['within_target_auroc']:.3f} | {r['auprc']:.3f} |"
        )
    a("")
    a("![pooled vs within-target AUROC](figures/auroc_pooled_vs_within.png)")
    a("")

    a("### The trivial baseline")
    a("")
    a("Section 8.3 requires a deliberately trivial baseline so improvements are")
    a("measured against something rather than against zero.")
    a("")
    a("| Baseline | Pooled AUROC | Within-target AUROC |")
    a("|---|---|---|")
    for _, r in baseline_rows.iterrows():
        a(f"| `{r['feature']}` | {r['pooled_auroc']:.3f} | {r['within_target_auroc']:.3f} |")
    a("")
    best_base = float(baseline_rows["within_target_auroc"].max())
    a(f"The best trivial baseline reaches {best_base:.3f} within-target AUROC and")
    a(f"the best real metric {best_row['within_target_auroc']:.3f}, so genuine")
    a(f"headroom over a non-predictor is **{best_row['within_target_auroc'] - best_base:+.3f}**.")
    a("")

    a("## Per-target breakdown: where it works and where it fails")
    a("")
    a(f"Within-target AUROC of `{best_row['feature']}`:")
    a("")
    a("| Target | n | AUROC |")
    a("|---|---|---|")
    for tgt, val in sorted(best_per_target.items(), key=lambda kv: -kv[1]):
        a(f"| {tgt} | {per_target_n.get(tgt, 0)} | {val:.3f} |")
    a("")
    excluded = sorted(set(per_target_n) - set(best_per_target))
    if excluded:
        a(
            f"Excluded for having only one outcome class: {', '.join(excluded)}. "
            "These contribute no AUROC and are **not** scored as 0.5."
        )
        a("")
    worse = {k: v for k, v in best_per_target.items() if v < 0.5}
    if worse:
        a(
            f"**The metric is worse than chance on {len(worse)} of "
            f"{len(best_per_target)} targets**: "
            + ", ".join(f"{k} ({v:.2f})" for k, v in sorted(worse.items(), key=lambda kv: kv[1]))
            + "."
        )
        a("A metric that inverts on some targets cannot be used as a hard filter")
        a("without a per-target sanity check.")
    else:
        a("The metric is at or above chance on every target where it is computable.")
    a("")
    a("![per-target AUROC](figures/per_target_auroc.png)")
    a("")

    a("## Calibration")
    a("")
    a(
        f"Expected calibration error of the leave-one-target-out model: "
        f"**{ece:.3f}** over {len(reliability)} populated bins."
    )
    a("")
    a("| Predicted range | n | Mean predicted | Observed binder rate |")
    a("|---|---|---|---|")
    for r in reliability:
        a(
            f"| {r['bin_lo']:.1f}-{r['bin_hi']:.1f} | {int(r['n'])} | "
            f"{r['mean_predicted']:.3f} | {r['observed_rate']:.3f} |"
        )
    a("")
    a("![calibration](figures/calibration.png)")
    a("")
    a("Raw ipSAE is not a probability and is not calibrated as one. Only the")
    a("fitted model output is treated as a probability above.")
    a("")

    a("## Recommended operating point")
    a("")
    a(f"On `{best_row['feature']}`, maximising the Youden J statistic:")
    a("")
    a(f"- threshold **{operating['threshold']:.3f}**")
    a(f"- sensitivity {operating['sensitivity']:.3f}, specificity {operating['specificity']:.3f}")
    a(f"- precision {operating['precision']:.3f}, recall {operating['recall']:.3f}")
    a(f"- selects {operating['n_selected']} of {operating['n_total']} designs")
    a("")
    a(
        f"At this threshold about {100 * operating['precision']:.0f}% of selected "
        f"designs were measured binders, against a base rate of "
        f"{100 * n_pos / n:.1f}%. That is a real improvement, and it still means "
        "most selected designs do not bind."
    )
    a("")

    a("## Conclusions")
    a("")
    a(
        f"1. **The metrics carry real signal.** `{best_row['feature']}` reaches "
        f"{best_row['within_target_auroc']:.3f} within-target AUROC against "
        f"{best_base:.3f} for the best trivial baseline, and the effect survives "
        "grouping by target in both the folds and the bootstrap."
    )
    a(
        "2. **Average the predictors; do not learn weights over them.** The "
        "unweighted mean of ten predictors beat every individual predictor, and a "
        "leave-one-target-out logistic regression over all 27 metric columns did "
        "worse than that mean. On fifteen targets, relative predictor reliability "
        "does not transfer; the average does."
    )
    a(
        "3. **Check pooled against within-target AUROC per metric, because the bias "
        "is signed.** DockQ metrics look up to 0.08 better pooled than they are "
        "within a target; ipSAE metrics mostly look slightly worse. Reporting only "
        "pooled AUROC would have overstated one family and understated the other."
    )
    if worse:
        a(
            f"4. **No metric is safe as a universal hard filter.** The best metric is "
            f"at or below chance on {len(worse)} of {len(best_per_target)} targets, "
            "so a fixed cut-off would discard good designs on those targets."
        )
    else:
        a(
            "4. The best metric is at or above chance on every target where it can be "
            "computed, which is a weaker claim than it sounds given how few targets "
            "there are."
        )
    a(
        f"5. **Enrichment is real and modest.** At the recommended threshold, "
        f"{100 * operating['precision']:.0f}% of selected designs were binders "
        f"against a {100 * n_pos / n:.1f}% base rate: roughly "
        f"{operating['precision'] / (n_pos / n):.1f}x enrichment, and still a "
        "majority of selected designs that do not bind."
    )
    a(
        "6. **The wet lab agrees with itself only 89% of the time**, which bounds "
        "what any in-silico metric can be asked to achieve."
    )
    a("")
    a("## Limitations")
    a("")
    a("- One campaign, two CROs, 16 targets, miniproteins of 50-120 residues only.")
    a("- These designs were not produced by this repo pipeline, so the thresholds")
    a("  transfer only as far as the metric definitions match.")
    a("- `binder_final` is an adjudicated label over two disagreeing assays, not a")
    a("  direct measurement. Per-vendor calls would give a slightly different answer.")
    a("- Several K_D values in the release are apparent rather than true (oligomeric")
    a("  analytes, differing antigen forms), so this study uses the binary call only.")
    a("- Logistic regression with median imputation and no tuning. A stronger model")
    a("  might extract more, though the within-target ceiling suggests the headroom")
    a("  is small.")
    a("")

    out = OUT / "REPORT.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    return out


def main(force_download: bool = False) -> int:
    """Run the whole study. Returns a process exit code."""
    logging.getLogger().setLevel(logging.INFO)
    path = fetch_summary(force=force_download)
    df = build_table(path)

    if not no_target_appears_in_both_folds(df):
        raise AssertionError("grouped split is leaking targets between folds")

    feats = feature_columns(df)
    y = df[LABEL].to_numpy(dtype=int)
    groups = df[GROUP].to_numpy()

    rows: list[dict[str, object]] = []
    for col, family in feats.items():
        s = df[col].to_numpy(dtype=float)
        ok = ~np.isnan(s)
        if ok.sum() < 50 or len(np.unique(y[ok])) < 2:
            continue
        point, lo, hi = grouped_bootstrap_ci(y[ok], s[ok], groups[ok])
        wt, _per, _n = within_target_auroc(y[ok], s[ok], groups[ok])
        rows.append(
            {
                "feature": col,
                "family": family,
                "pooled_auroc": point,
                "auroc_lo": lo,
                "auroc_hi": hi,
                "within_target_auroc": wt,
                "auprc": _auprc(y[ok], s[ok]),
                "n": int(ok.sum()),
            }
        )
    single = pd.DataFrame(rows)
    single.to_csv(OUT / "single_metric_results.csv", index=False)
    log.info("evaluated %d single metrics", len(single))

    real = single[single["family"] != "trivial baseline"]
    baselines = single[single["family"] == "trivial baseline"]
    best_row = real.sort_values("within_target_auroc", ascending=False).iloc[0]

    bs = df[best_row["feature"]].to_numpy(dtype=float)
    ok = ~np.isnan(bs)
    _, best_per_target, per_target_n = within_target_auroc(y[ok], bs[ok], groups[ok])
    operating = recommend_threshold(y[ok], bs[ok])

    model_feats = [c for c in feats if feats[c] != "trivial baseline"]
    oof_p, oof_y, oof_g, used = leave_one_target_out(df, model_feats)
    m_pooled, m_lo, m_hi = grouped_bootstrap_ci(oof_y, oof_p, oof_g)
    m_within, _, _ = within_target_auroc(oof_y, oof_p, oof_g)
    ece, reliability = expected_calibration_error(oof_y, oof_p)
    model_stats = {
        "pooled_auroc": m_pooled,
        "auroc_lo": m_lo,
        "auroc_hi": m_hi,
        "within_target_auroc": m_within,
        "ece": ece,
        "n_features": float(len(used)),
    }

    figs = make_figures(df, single, reliability, best_per_target)

    calib = {
        "source": "Anthropic/claude-protein-binder-design design_summary.csv (CC BY 4.0)",
        "n_designs": int(len(df)),
        "n_targets": int(df[GROUP].nunique()),
        "base_rate": float(df[LABEL].mean()),
        "best_single_metric": str(best_row["feature"]),
        "best_single_pooled_auroc": float(best_row["pooled_auroc"]),
        "best_single_within_target_auroc": float(best_row["within_target_auroc"]),
        "model": model_stats,
        "operating_point": operating,
        "vendor_agreement_ceiling": 0.890,
        "figures": figs,
    }
    (OUT / "calibration.json").write_text(json.dumps(calib, indent=2) + "\n", encoding="utf-8")

    report = write_report(
        df,
        single,
        best_row,
        best_per_target,
        per_target_n,
        model_stats,
        reliability,
        ece,
        operating,
        baselines,
    )
    log.info("wrote %s and %d figure(s)", report, len(figs))

    print(f"\nBEST SINGLE METRIC: {best_row['feature']}")
    print(
        f"  pooled AUROC        {best_row['pooled_auroc']:.3f} "
        f"[{best_row['auroc_lo']:.3f}, {best_row['auroc_hi']:.3f}]"
    )
    print(f"  within-target AUROC {best_row['within_target_auroc']:.3f}")
    print(f"  LOTO model within-target {m_within:.3f} (pooled {m_pooled:.3f}, ECE {ece:.3f})")
    print(f"  best trivial baseline within-target {baselines['within_target_auroc'].max():.3f}")
    return 0
